### ISSUE TITLE
Internal server error saving plugin settings when allowAdminChanges is false

### ISSUE THREAD

**Issue by hannahwoodward** [FosterCommerce/shipstation-connect#10]
We're using this plugin on a site where we have (on production):
- allowAdminChanges set to false
- projectConfig enabled 

The client has gone to add their Shipstation username & password in the plugin settings and found that it errored when they clicked save. From the logs, it looks like the error is caused by the Shipstation plugin trying to (unsuccessfully) write to the project config file (project.yaml). Would it be possible to instead save these plugin settings in the DB?

**Comment by johnnynotsolucky** [comment]
@hannahwoodward I've made a change (v1.2.4) to the plugins settings to allow environment variables be stored for the username and password fields. 

The problem is expected behaviour. With this change you can save the username/password as environment variables and have that committed to project.yaml, and add the environment variables to the production environment:
 
![Screenshot from 2019-10-28 12-46-10](https://user-images.githubusercontent.com/4161106/67672626-09ade700-f981-11e9-95af-f2423b0557e3.png)

**Comment by hannahwoodward** [comment]
That works for me - thank you!
