### ISSUE TITLE
Orders not passing to Shipstation

### ISSUE THREAD

**Issue by iamtompickering** [FosterCommerce/shipstation-connect#36]
I've followed the setup instructions that you have provided and also can confirm that the Custom Store connection is successful, but I cannot see any of my test orders being carried across into my ShipStation account. 

I've checked the logs but cannot see any errors in there. 

Orders have the Shipping Info matrix block included in them with the correct fields and I've matched up the order statuses and orders, so not sure what else I could be missing??!

Any help on this would be greatly appreciated.

**Comment by sjcallender** [comment]
@iamtompickering - In your site's ShipStation Connect settings, there's a Custom XML Page URL. That's the URL ShipStation needs. Is that what you're using?

You can test that endpoint with a URL like so:
`https://example.com/actions/shipstationconnect/orders/process?store=REPLACE_ME&SS-UserName=REPLACE_ME&SS-Password=REPLACE_ME&action=export&start_date=01/01/2021+00:00&end_date=12/31/2021+23:59&page=`

**Comment by iamtompickering** [comment]
@sjcallender yes I have included this in my Custom Store settings and when I click 'Test Connection' it says the connection is successful. 

But when I go to that URL and add the query strings you have stated above (replacing the necessary parts) it comes up with `{"error":"Invalid ShipStation username or password."}` 

I've double checked the username and password in the plugin settings and they are all the same as what I've added in the Custom Store settings. So seems strange it should come up with that error

**Comment by johnnynotsolucky** [comment]
@iamtompickering this could be because the test orders were created before the ShipStation store was set up. I think that perhaps the start_date that ShipStation passes to the endpoint may be later than the `dateUpdated` value for your orders.

If Test Connection works, it likely means that ShipStation made a request for export and received a HTTP 200 response, which is expected.

To test a request to export orders you can use [curl](https://curl.se/), [Postman](https://www.postman.com/downloads/) or something similar.

For curl, you'll need to generate the Authorization token which is just a base64 encoded string of `username:password`. DebugBear has a nice [tool](https://www.debugbear.com/basic-auth-header-generator) for this.

```
curl \
--request GET 'https://mysite.com/actions/shipstationconnect/orders/process?action=export' \
--header 'Authorization: Basic dHlyb25lOnR5cm9uZQ=='
```

This should return XML content with your orders. I've excluded the start_date and end_dates, so the plugin should return all your orders split into pages.

For Postman:

![image](https://user-images.githubusercontent.com/4161106/141933478-e407865c-36c8-4bc7-af17-69dd07dc16f1.png)

If these requests return orders correctly, I think the next thing to do is update your orders so that they have a new `dateUpdated` field which will fall inside the date range ShipStation is querying for.

**Comment by iamtompickering** [comment]
@johnnynotsolucky Thanks for this, I've tested it in Postman now and the orders have now carried across to ShipStation. 

I'm not sure what you mean by updating the `dateUpdated` field though, are you suggesting to create a new field in the `shippingInfo` matrix field? Could you just explain this a little more for me?

Thanks!

**Comment by sjcallender** [comment]
By `dateUpdated` field he's referring to the `dateUpdated` value on an order element. If you resave an order from the control panel, the `dateUpdated` value will get a new value. No need to add a new custom field for it.
