### ISSUE TITLE
Exclude Adjustments from XML

### ISSUE THREAD

**Issue by smockensturm** [FosterCommerce/shipstation-connect#49]
Hey there. How much trouble would it be to exclude promotions from the line items in the XML that Shipstation consumes?

Or like, if it doesn't have an SKU don't include it in the payload?

These are appearing on labels and causing some confusion.

Thanks.

**Comment by smockensturm** [comment]
Answer: not too much trouble. Comment out line 122 in the Xml.php service.

Why are you sending discount / adjustment data to Shipstation?

**Comment by fantasticmachine** [comment]
Hey @smockensturm 
Firstly, sorry for the long delay in responding. It's been a very busy few months at Foster Commerce and we are attempting to catch up with issues around other commitments.

I can't answer the question as to why we are sending the discount/adjustment data to Shipstation right now but it's something we will look into. There may be a reason for it, or it may just be an oversight. If that info is finding its way on to labels then it's most likely an oversight.

**Comment by fantasticmachine** [comment]
Hi @smockensturm I've been looking into this but have some difficulty since I can't create labels without a shipping provider (and we don't have one!). I'm reluctant to remove that code from Xml.php because I don't exactly know how that might impact other users. I'm also picking this up from the original developer and there is no documentation for this aspect of the code. But it's possible we can add a config variable or a switch to enable/disable the discounts being sent in the XML.

We also found this FAQ in the Shipstation help center which might be of help to you https://help.shipstation.com/hc/en-us/articles/360045864291-How-do-I-prevent-coupons-from-printing-on-packing-slips-

The existence of that article seems to imply that sending the coupon data is normal which makes me more inclined to leave it for the moment.

**Comment by smockensturm** [comment]
Hello @fantasticmachine That's cool. I get it. Probably going to fork this for making some other mods. Thanks for running it down and getting back though.

**Comment by johnnynotsolucky** [comment]
For posterity - We generally should be sending discounts/adjustments as line items. If senders are generating packing slips as a slip/invoice combo for recipients, then those adjustments would be necessary. Also, when dealing with customs, you'll want to include all the details about the items being shipped, and this includes discounts paid.
