### ISSUE TITLE
Processing Short Numbers Only?

### ISSUE THREAD

**Issue by smockensturm** [FosterCommerce/shipstation-connect#59]
Hey there, we have a situation with order numbers.

```
82fceda3cf3b9a66d2e2d61fea858c19
82fcedad331f3468434f819d9786457d
```

ShipStation Connect (I think) sees these as the same number and won't process the second one. How can we get ShipStation to process these seemingly duplicate numbers.

Weird, huh?

**Comment by johnnynotsolucky** [comment]
Hi @smockensturm, I'll take a look at this on Monday first thing.

**Comment by johnnynotsolucky** [comment]
@smockensturm, by default the order export uses the order reference number which is a user-defined field. Commerce sets it to `{{number[:7]}}` by default. Shortening the order number drastically increases the chance of a collision with higher order counts.

There are 2 possibilities to resolve this.

The first is to update the reference field in your store config so that you can guarantee its uniqueness.

Alternatively, if you have a site module on that site, you can add an event listener to override the value with the full order number:

```php
use yii\base\Event;
use fostercommerce\shipstationconnect\services\Xml;
use fostercommerce\shipstationconnect\events\OrderFieldEvent;

Event::on(
    Xml::class,
    Xml::ORDER_FIELD_EVENT,
    function (OrderFieldEvent $e) {
        if ($e->fieldName === OrderFieldEvent::FIELD_ORDER_NUMBER) {
            $e->value = $e->order->number;
        }
    }
);
```
